# Generated by Django 4.0.3 on 2022-04-02 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('new', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mazda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('reg_num', models.CharField(max_length=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mazda_app.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='users',
            field=models.ManyToManyField(to='mazda_app.users'),
        ),
    ]
