# Generated by Django 4.0.3 on 2022-04-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazda_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
