# Generated by Django 4.0.3 on 2022-04-07 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mazda_app', '0002_alter_users_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name_plural': 'car'},
        ),
        migrations.AlterModelOptions(
            name='mazda',
            options={'verbose_name_plural': 'mazda'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'user'},
        ),
        migrations.RemoveField(
            model_name='mazda',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mazda_app.mazda'),
            preserve_default=False,
        ),
    ]
